version: "3.5"

volumes:
  postgresdata:
  mavencache:

networks:
  default:
    name: appnetwork
    ipam:
      config:
        - subnet: "172.16.238.0/24"

services:
  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: "sample-app"
      POSTGRES_PASSWORD: "sample-app-password"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile.app
    hostname: app
    networks:
      default:
        ipv4_address: 172.16.238.10
    volumes:
      - ./app:/app
      - mavencache:/root/.m2/repository
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DOCKER_ENV: "true"
      FRONTEND_HOST: "172.16.238.9:8080"
      JDBC_URL: "jdbc:postgresql://postgres/sample-app?user=sample-app&password=sample-app-password"

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile.frontend
    hostname: frontend
    networks:
      default:
        ipv4_address: 172.16.238.9
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    environment:
      DOCKER_ENV: "true"
      BACKEND_HOST: "172.16.238.10:3000/api"
      PORT: 8080
    extra_hosts:
      - host.docker.internal:host-gateway
