FROM node:18-alpine

WORKDIR /app

# EXPOSE is merely a hint that a certain ports are useful
EXPOSE 8080

ENV PATH /app/node_modules/.bin:$PATH

COPY ./frontend/package*.json /app/

RUN npm install

# Copy project to container
COPY ./frontend /app

# Start the node dev server
CMD [ "npm", "start" ]
